


version: "3.6"
services:
  ad-hoc:
    build:
      context: ./
      dockerfile: docker/ad-hoc/Dockerfile
    # image: jupyterlab
    container_name: ad-hoc
    ports:
      - 8888:8888
    environment:
      - PYTHONPATH=/opt/workspace/apps:/opt/workspace/scripts:/opt/workspace/dags
      - ADLS_adlsthuehomelakehousedev_access_key=$data_lake_access_key
    volumes:
      - ./src/ad-hoc:/opt/workspace
      - ./src/airflow_dags:/opt/workspace/dags
      - ./settings/jupyter:/root/.vscode-server
    networks:
      - my_persistent_network 
    depends_on:
      - spark-master
  spark-master:
    build:
      context: ./
      dockerfile: docker/spark-master/Dockerfile
    # image: spark-master
    container_name: spark-master
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - 8089:8080
      - 7077:7077
    networks:
      - my_persistent_network  
  spark-worker-1:
    build:
      context: ./
      dockerfile: docker/spark-worker/Dockerfile
    # image: spark-worker
    container_name: spark-worker-1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    # volumes:
    #   - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - my_persistent_network  

  postgresql:
    # image: docker.io/bitnami/postgresql:15
    build:
      context: ./
      dockerfile: docker/postgresql/Dockerfile
    volumes:
      - ./data/postgresql_data:/bitnami/postgresql/data
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '5432:5432'
    networks:
      - my_persistent_network 
  redis:
    # image: docker.io/bitnami/redis:7.0
    build:
      context: ./
      dockerfile: docker/redis/Dockerfile
    volumes:
      - './data/redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_persistent_network 
  airflow-scheduler:
    build:
      context: ./
      dockerfile: docker/airflow-scheduler/Dockerfile
    # image: airflow-scheduler
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      # - PYTHONPATH=/opt/bitnami/airflow/dags:/opt/bitnami/airflow/plugins:/opt/bitnami/python/scripts
    volumes:
      - ./src/airflow_dags:/opt/bitnami/airflow/dags
      - ./src/jupyter/apps:/opt/bitnami/spark/apps
      # - ./src/jupyter/scripts:/opt/bitnami/python/scripts
      # - ./dependencies/requirements.txt:/bitnami/python/requirements.txt
    networks:
      - my_persistent_network 
  airflow-worker:
    build:
      context: ./
      dockerfile: docker/airflow-worker/Dockerfile
    # image: airflow-worker
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      - PYTHONPATH=/opt/bitnami/airflow/dags:/opt/bitnami/airflow/plugins:/opt/bitnami/python/scripts
      - ADLS_adlsthuehomelakehousedev_access_key=$data_lake_access_key
    volumes:
      - ./src/airflow_dags:/opt/bitnami/airflow/dags
      - ./src/ad-hoc/apps:/opt/bitnami/spark/apps
      - ./src/ad-hoc/scripts:/opt/bitnami/python/scripts
      # - ./dependencies/requirements.txt:/bitnami/python/requirements.txt
    networks:
      - my_persistent_network 
  airflow:
    build:
      context: ./
      dockerfile: docker/airflow/Dockerfile
    # image: airflow
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_PASSWORD=bitnami
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      # - PYTHONPATH=/opt/bitnami/airflow/dags:/opt/bitnami/airflow/plugins:/opt/bitnami/python/scripts
      # - AIRFLOW_HOME=/opt/bitnami/airflow
    volumes:
      - ./src/airflow_dags:/opt/bitnami/airflow/dags
      - ./settings/airflow:/.vscode-server
      # - ./src/jupyter/apps:/opt/bitnami/spark/apps
      # - ./src/jupyter/scripts:/opt/bitnami/python/scripts
      # - ./dependencies/requirements.txt:/bitnami/python/requirements.txt
    ports:
      - '9080:8080' 
    networks:
      - my_persistent_network 

networks:
  my_persistent_network:
    driver: bridge