version: "3.6"
volumes:
  broker: null
  esdata: null
  mysqldata: null
  zkdata: null
services:
# Processing
  ad-hoc:
    extends:
      file: docker-compose-processing.yaml
      service: ad-hoc
    networks:
    - my_persistent_network 
  spark-master:
    extends:
      file: docker-compose-processing.yaml
      service: spark-master
    networks:
    - my_persistent_network  
  spark-worker-1:
    extends:
      file: docker-compose-processing.yaml
      service: spark-worker-1
    networks:
    - my_persistent_network 

  postgresql:
    extends:
      file: docker-compose-processing.yaml
      service: postgresql
    networks:
    - my_persistent_network 
  redis:
    extends:
      file: docker-compose-processing.yaml
      service: redis
    networks:
    - my_persistent_network 
  airflow-scheduler:
    extends:
      file: docker-compose-processing.yaml
      service: airflow-scheduler
    networks:
    - my_persistent_network 
  airflow-worker:
    extends:
      file: docker-compose-processing.yaml
      service: airflow-worker
    networks:
    - my_persistent_network  
  airflow:
    extends:
      file: docker-compose-processing.yaml
      service: airflow
    networks:
    - my_persistent_network 
  

# Analytics
  trino-coordinator:
    extends:
      file: docker-compose-analytics.yaml
      service: trino-coordinator
    networks:
    - my_persistent_network  

  superset:
    extends:
      file: docker-compose-analytics.yaml
      service: superset
    networks:
    - my_persistent_network  

  metastore_db:
    extends:
      file: docker-compose-analytics.yaml
      service: metastore_db
    networks:
    - my_persistent_network  

  hive-metastore:
    extends:
      file: docker-compose-analytics.yaml
      service: hive-metastore
    networks:
    - my_persistent_network  
  

# Datahub
  datahub-actions:
    extends:
      file: docker-compose-datahub.yaml
      service: datahub-actions
    networks:
    - my_persistent_network
  datahub-frontend-react:
    extends:
      file: docker-compose-datahub.yaml
      service: datahub-frontend-react
    networks:
    - my_persistent_network
  datahub-gms:
    extends:
      file: docker-compose-datahub.yaml
      service: datahub-gms
    networks:
    - my_persistent_network
  datahub-upgrade:
    extends:
      file: docker-compose-datahub.yaml
      service: datahub-upgrade
    networks:
    - my_persistent_network
  elasticsearch:  
    extends:
      file: docker-compose-datahub.yaml
      service: elasticsearch
    networks:
    - my_persistent_network
  elasticsearch-setup:
    extends:
      file: docker-compose-datahub.yaml
      service: elasticsearch-setup
    networks:
    - my_persistent_network
  kafka-setup:
    extends:
      file: docker-compose-datahub.yaml
      service: kafka-setup
    networks:
    - my_persistent_network
  mysql:
    extends:
      file: docker-compose-datahub.yaml
      service: mysql
    networks:
    - my_persistent_network
  mysql-setup:
    extends:
      file: docker-compose-datahub.yaml
      service: mysql-setup
    networks:
    - my_persistent_network
  schema-registry:
    extends:
      file: docker-compose-datahub.yaml
      service: schema-registry
    networks:
    - my_persistent_network
  zookeeper:
    extends:
      file: docker-compose-datahub.yaml
      service: zookeeper
    networks:
    - my_persistent_network
  zookeeper-setup:
    extends:
      file: docker-compose-datahub.yaml
      service: zookeeper-setup
    networks:
    - my_persistent_network
  

networks:
  my_persistent_network:
    driver: bridge